name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y ninja-build meson

    - name: Configure build
      run: meson setup build

    - name: Build
      run: meson compile -C build

    - name: Run tests
      run: meson test -C build

